### ISSUE TITLE
Deprecation warning thrown by PyTest

### ISSUE THREAD

**Issue by vipulgupta2048** [scrapinghub/spidermon#184]
On running, Pytest it throws some deprecation warning in files `validate.py` and `union.py` of `schematics`, It seems some functions got deprecated since Python 3 but would like a `go-ahead` if I should be solving this by applying PyTests suggestion. Here's the detailed error. 

```
  /home/vipulgupta2048/.local/lib/python3.6/site-packages/schematics/validate.py:123: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    if len(inspect.getargspec(func).args) < argcount:

  /home/vipulgupta2048/.local/lib/python3.6/site-packages/schematics/types/union.py:20: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    args.update(inspect.getargspec(cls.__init__).args[1:])
```

Will open some more issues, to at least problems that we can be fixing.

**Comment by rennerocha** [comment]
@vipulgupta2048 
This (DeprecationWarning)[https://docs.python.org/3/library/exceptions.html#DeprecationWarning] is raised by inspect.getargspec function and it is used by schematics. So it is a schematic library problem that needs to be fixed in their codebase (not related to Spidermon). We could ignore it in tox.ini, but I believe it is worthy to have it in Spidermon tests so we are warned if we are using some deprecated function as well.
