### ISSUE TITLE
'AttributeError: Spider object has no attribute 'stats_history'

### ISSUE THREAD

**Issue by paulfsheridan** [scrapinghub/spidermon#186]
I'm trying to run a 'HistoryMonitor' monitor similar to the one on [this page](https://spidermon.readthedocs.io/en/latest/getting-started.html) however when I run in production I receive this error: 'AttributeError: Spider object has no attribute 'stats_history', I have also enabled the DotScrapy Persistence addon.

**Comment by rennerocha** [comment]
This happens because `STATS_CLASS` setting is being overriden by Scrapy Cloud from `spidermon.contrib.stats.statscollectors.LocalStorageStatsHistoryCollector` to `sh_scrapy.stats.HubStorageStatsCollector`, so `stats_history` attribute is never included on spider instance opening.

To be able to use it in Scrapy Cloud, you need to go to [Spider Settings](https://support.scrapinghub.com/support/solutions/articles/22000200670-customizing-scrapy-settings-in-scrapy-cloud) section, and manually include the correct `STATS_CLASS` there.

The drawback of this approach is that your job stats will not be uploaded to Scrapy Cloud interface and will be available only in the job logs.

**Comment by paulfsheridan** [comment]
Great thanks for this.

**Comment by prashantenprocon** [comment]
Is there any authentication require where adding on scrapy cloud in STATS_CLASS.

**Comment by Gallaecio** [comment]
Scrapy Cloud overrides `STATS_CLASS`. If your issue is that you define a custom `STATS_CLASS` in settings.py but it does not get picked up, it’s because of that; you need to define `STATS_CLASS` in the spider settings in Scrapy Cloud itself.
