### ISSUE TITLE
Report test coverage

### ISSUE THREAD

**Issue by Gallaecio** [scrapinghub/spidermon#235]
It would be great if Spidermon could generate coverage data when running tests.

Moreover, if the project is configured to to work with https://codecov.io/, pull requests could get a message reporting how they affect test coverage.

**Comment by vipulgupta2048** [comment]
Excellent idea, @Gallaecio 
We do have `pytest-cov` plugin added into the pytest suite. Ain't much help since we have a lot of Python files. I think, having a quick report while making PR's will be useful to both the contributor and maintainers in the long run.

**Comment by rennerocha** [comment]
This should be fixed with https://github.com/scrapinghub/spidermon/pull/236

There is a warning `No coverage uploaded for pull request base` in coverage bot comment. Not sure if this is will appear only because we never have a build that run coverage in master before and it will start working after merging this PR.

@Gallaecio do you have any comment on this?

**Comment by Gallaecio** [comment]
@rennerocha I agree with you, I think it should start working once merged. That said, I’ve been [unable to enable Codecov for Protego](https://codecov.io/gh/scrapy/protego) yet, so I’m far from an expert :)

**Comment by rennerocha** [comment]
It is merged. I hope it works :-)
