### ISSUE TITLE
ItemCountMonitor fails if SPIDERMON_MIN_ITEMS is 0

### ISSUE THREAD

**Issue by phrfpeixoto** [scrapinghub/spidermon#278]
Hello,

When working on a spider using SPIDERMON_MIN_ITEMS I stumbled upon this:

https://github.com/scrapinghub/spidermon/blob/cb7b80aa30ae8af97a05b072a5725dbcd7067c74/spidermon/contrib/scrapy/monitors.py#L25-L40

On that code, line 36 will always fail if the constant `SPIDERMON_MIN_ITEMS` is not defined, **or even worst, defined as 0 (zero).**

**Comment by rennerocha** [comment]
Hello @phrfpeixoto,
This is the expected behavior and is [documented](https://spidermon.readthedocs.io/en/latest/monitors.html#spidermon.contrib.scrapy.monitors.ItemCountMonitor).
If we add this monitor we necessarily need to define `SPIDERMON_MIN_ITEMS` or else a `NotConfigured` exception will be raised. Defining it as zero doesn't make sense either, so it will raise the exception too.
